### ISSUE TITLE
big bug ples fix it pleas

### ISSUE THREAD

**Issue by Shortninja66** [kjluke/Poker-Runner#34]
hallo i are use the program for my linux microsoft serber for my server and there is are an ishoo with the progrem. it do not run it in the serber and the server wont run it. i think bug fix is in the program. i are an 48 years old men from somalia who love to play on microsoft linux serber server. sorry for bad england i use to speak you. if fix you can fix the I can be very happy if fix can be thank

**Comment by kjluke** [comment]
Gavin wtf
